# Generated by Django 3.2.18 on 2025-02-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='loading_file',
            field=models.BooleanField(default=False),
        ),
    ]
