# Generated by Django 3.2.18 on 2024-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='untitled document', max_length=200),
        ),
        migrations.AddField(
            model_name='layer',
            name='title',
            field=models.CharField(default='untitled layer', max_length=200),
        ),
        migrations.AddField(
            model_name='map',
            name='item_lookup',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('initializing...', 'initializing...'), ('ready', 'ready')], default='not started', max_length=50),
        ),
        migrations.AddField(
            model_name='region',
            name='georeferenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='title',
            field=models.CharField(default='untitled region', max_length=200),
        ),
    ]
