# Generated by Django 3.2.18 on 2025-01-14 22:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241119_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=2),
        ),
        migrations.AddField(
            model_name='document',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='image_size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=2),
        ),
        migrations.AddField(
            model_name='region',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
