# Generated by Django 3.2.18 on 2025-01-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250114_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='extent',
        ),
    ]
