# Generated by Django 3.2.18 on 2025-03-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_map_loading_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=200, null=True)),
                ("display_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "  Region Categories",
            },
        ),
        migrations.AddField(
            model_name="region",
            name="skipped",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="region",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.regioncategory",
            ),
        ),
    ]
