# Generated by Django 3.2.18 on 2025-06-04 18:13

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250327_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='layers'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='layerset',
            name='mosaic_geotiff',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='mosaics'),
        ),
        migrations.AlterField(
            model_name='layerset',
            name='mosaic_json',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='mosaics'),
        ),
        migrations.AlterField(
            model_name='region',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='regions'),
        ),
        migrations.AlterField(
            model_name='region',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=255, null=True, storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='thumbnails'),
        ),
    ]
