# Generated by Django 3.2.18 on 2025-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20250605_2015"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="completion_pct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="map",
            name="document_ct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="map",
            name="layer_ct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="map",
            name="multimask_ct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="map",
            name="multimask_rank",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name="map",
            name="nonmap_ct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="map",
            name="prepared_ct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="map",
            name="region_ct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="map",
            name="skip_ct",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="map",
            name="unprepared_ct",
            field=models.IntegerField(default=0),
        ),
    ]
