# Generated by Django 3.2.18 on 2025-01-20 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_layer_extent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='day',
        ),
        migrations.RemoveField(
            model_name='map',
            name='document_lookup',
        ),
        migrations.RemoveField(
            model_name='map',
            name='layer_lookup',
        ),
    ]
