# Generated by Django 3.2.18 on 2025-09-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250801_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='tilejson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layerset',
            name='tilejson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
