# Generated by Django 3.2.18 on 2025-01-23 20:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import ohmg.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0015_alter_layerset_map'),
        ('core', '0007_auto_20250120_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerSetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'LayerSet Categories',
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='layerset2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georeference.layerset'),
        ),
        migrations.CreateModel(
            name='LayerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimask', models.JSONField(blank=True, null=True)),
                ('mosaic_geotiff', models.FileField(blank=True, max_length=255, null=True, storage=ohmg.core.storages.OverwriteStorage(), upload_to='mosaics')),
                ('mosaic_json', models.FileField(blank=True, max_length=255, null=True, storage=ohmg.core.storages.OverwriteStorage(), upload_to='mosaics')),
                ('extent', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.layersetcategory')),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.map')),
            ],
        ),
    ]
