# Generated by Django 4.2.27 on 2026-03-11 17:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250915_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='mask',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
