# Generated by Django 3.2.18 on 2025-01-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250123_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layerset',
            options={'verbose_name_plural': 'LayerSets'},
        ),
        migrations.AlterField(
            model_name='layer',
            name='layerset2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.layerset'),
        ),
    ]
