# Generated by Django 4.2.27 on 2026-04-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_layer_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerset',
            name='multimask',
        ),
    ]
