# Generated by Django 4.2.27 on 2026-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_layerset_multimask'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='main_layer_ct',
            field=models.IntegerField(default=0),
        ),
    ]
