# Generated by Django 3.2.18 on 2025-01-24 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250124_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='layerset',
        ),
    ]
