# Generated by Django 4.2.27 on 2026-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_map_main_layer_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerset',
            name='xyz_tiles_prefix',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
