# Generated by Django 3.2.18 on 2025-02-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_layer_layerset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='gcp_group',
        ),
    ]
