# Generated by Django 4.2.27 on 2026-06-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_layerset_xyz_tiles_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('use_helmert', 'Can use Helmert transformation'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
