# Generated by Django 4.2.27 on 2026-06-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('use_helmert', 'Can use Helmert transformation'), ('queue_mosaic_cog', 'Can queue creation of mosaic COG'), ('queue_mosaic_xyz', 'Can queue creation of mosaic XYZ tileset'))},
        ),
        migrations.AddField(
            model_name='layerset',
            name='mosaic_geotiff_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layerset',
            name='multimask_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layerset',
            name='xyz_tiles_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
