# Generated by Django 4.2.27 on 2026-06-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_permissions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerset',
            name='mosaic_geotiff_date',
        ),
        migrations.RemoveField(
            model_name='layerset',
            name='xyz_tiles_date',
        ),
    ]
