# Generated by Django 4.2.27 on 2026-09-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_layerset_mosaic_geotiff_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='anisotropy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='gcp_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='GCP Count'),
        ),
        migrations.AddField(
            model_name='layer',
            name='rmse',
            field=models.FloatField(blank=True, null=True, verbose_name='RMSE'),
        ),
        migrations.AddField(
            model_name='layer',
            name='skew',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='transformation',
            field=models.CharField(blank=True, null=True),
        ),
    ]
