# Generated by Django 2.2.20 on 2023-03-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('state', 'State'), ('county', 'County'), ('parish', 'Parish'), ('borough', 'Borough'), ('census area', 'Census Area'), {'independent city', 'Independent City'}, ('city', 'City'), ('town', 'Town'), ('village', 'Village'), ('other', 'Other')], max_length=20)),
                ('display_name', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('volume_count', models.IntegerField(default=0, help_text='Number of volumes attached to this place')),
                ('volume_count_inclusive', models.IntegerField(default=0, help_text='Number of volumes attached to this place and any of its descendants')),
                ('direct_parents', models.ManyToManyField(to='places.Place')),
            ],
        ),
    ]
