# Generated by Django 3.2.18 on 2024-02-22 10:57

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.CharField(blank=True, max_length=200, null=True)),
                ("content", markdownx.models.MarkdownxField()),
            ],
        ),
    ]
