# Generated by Django 3.2.18 on 2025-07-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20250210_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
