# Generated by Django 3.2.18 on 2025-02-07 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('loc_insurancemaps', '0001_initial'), ('loc_insurancemaps', '0002_volume_mosaic_json'), ('loc_insurancemaps', '0003_volume_mosaic_preference'), ('loc_insurancemaps', '0004_auto_20240116_1016'), ('loc_insurancemaps', '0005_alter_volume_state'), ('loc_insurancemaps', '0006_auto_20250119_1307')]

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
