# Generated by Django 3.2.18 on 2024-01-16 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loc_insurancemaps', '0003_volume_mosaic_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='access',
            field=models.CharField(choices=[('none', 'none'), ('sponsor', 'sponsor'), ('any', 'any')], default='any', max_length=50),
        ),
        migrations.AddField(
            model_name='volume',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volume',
            name='loaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loaded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volume',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('initializing...', 'initializing...'), ('ready', 'ready')], default='not started', max_length=50),
        ),
    ]
