# Generated by Django 3.2.18 on 2025-01-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0005_alter_volume_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='loaded_by',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='locales',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='sponsor',
        ),
        migrations.DeleteModel(
            name='Sheet',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
