# Generated by Django 2.2.16 on 2021-07-16 19:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0031_auto_20201107_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCollectionItem',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'), ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'), ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'), ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'), ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'), ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'), ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'), ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New Hampshire', 'New Hampshire'), ('New Jersey', 'New Jersey'), ('New Mexico', 'New Mexico'), ('New York', 'New York'), ('North Carolina', 'North Carolina'), ('North Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'), ('Pennsylvania', 'Pennsylvania'), ('Rhode Island', 'Rhode Island'), ('South Carolina', 'South Carolina'), ('South Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'), ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West Virginia', 'West Virginia'), ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')], max_length=50)),
                ('year', models.IntegerField(choices=[(1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949)])),
                ('month', models.CharField(blank=True, choices=[('JAN.', 'JAN.'), ('FEB.', 'FEB.'), ('MAR.', 'MAR.'), ('APR.', 'APR.'), ('MAY.', 'MAY.'), ('JUN.', 'JUN.'), ('JUL.', 'JUL.'), ('AUG.', 'AUG.'), ('SEP.', 'SEP.'), ('OCT.', 'OCT.'), ('NOV.', 'NOV.'), ('DEC.', 'DEC.')], max_length=10, null=True)),
                ('volume_no', models.CharField(blank=True, max_length=5, null=True)),
                ('loc_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('file_count', models.IntegerField(blank=True, null=True)),
                ('iiif_manifest', models.CharField(blank=True, max_length=200, null=True)),
                ('loc_type', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='MapScan',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.Document')),
                ('sheet_no', models.CharField(blank=True, max_length=100, null=True)),
                ('loc_type', models.CharField(blank=True, max_length=25, null=True)),
                ('loc_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('is_index', models.BooleanField(blank=True, default=False, null=True)),
                ('iiif_service', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lc_insurancemaps.MapScan')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc_insurancemaps.MapCollectionItem')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
    ]
