exclude: .*migrations\/.*
repos:
-   repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.12.1
    hooks:
        - id: validate-pyproject
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
