import math

from django.test import tag
from osgeo import gdal

from ohmg.georeference.georeferencer import Georeferencer

from .base import OHMGTestCase


@tag("warp")
class HelmertTransformationTestCase(OHMGTestCase):
    """These tests assume an input image with width 5 and height 8.
    Two GCPs are used, which are placed vertical from each other
    near the left edge of the image."""

    img_width = 5
    img_height = 8

    ## Create 2 GCPs for use in each test. These original
    ## coordinates will place the image with 0 rotation and .5 scale
    ## in the initial test. Later cases will change the X and Y coords
    ## of each GCP to test against different angles, etc.

    ## 8 different permutations are tested altogether, the

    # note 1. GCP args are: geo x, geo y, geo z (not used), img x, img y
    # note 2: img y uses inverse y axis (per GCP convention)
    # note 3: The distance between GCPs is 5 which creates a 3,4,5
    # triangle during rotated permutations of the test (helpful)
    gcp1 = gdal.GCP(0, 2.5, 0, 1, 1)
    gcp2 = gdal.GCP(0, 0, 0, 1, 6)

    # this is the small angle of a 3/4/5 triangle

    def test_helmert_transformation_A(self):
        """This test was hand-created to place the mock 5x8 image
        into generic cartesian coordinate space such that:
        rotation = 0
        scale = .5
        x, y offset (top left corner) = 4.5, 7.5.

        All other tests were generated by modifying GCP inputs to this one
        and recording the output.
        """

        theta_345 = math.degrees(math.asin(3 / 5))

        ## this is a list of variables that define each position of the test
        ## the adjustment is applied to GCP1, which starts with geo position 0, 2.5
        ## x adjustment, y adjustment, target azimuth
        data_matrix = [
            (0, 2.5, 0, -0.5, 3),
            (2, 1.5, 90 - theta_345, 55, 55),
            (2.5, 0, 90, 55, 55),
            (2, -1.5, 90 + theta_345, 55, 55),
            (0, -2.5, 180, 55, 55),
            (-2, -1.5, 270 - theta_345, 55, 55),
            (-2.5, 0, 270, 55, 55),
            (-2, 1.5, 270 + theta_345, 55, 55),
        ]

        for gcpx, gcpy, target_azimuth, x_offset, y_offset in data_matrix:
            gcp2 = gdal.GCP(0, 0, 0, 1, 6)
            gcp1 = gdal.GCP(gcpx, gcpy, 0, 1, 1)

            g = Georeferencer(crs="EPSG:3857", transformation="helmert", gcps_gdal=[gcp1, gcp2])

            scale = g._calculate_scale()
            self.assertEqual(scale, 0.5)

            azimuth = g._calculate_azimuth(img_height=self.img_height)
            self.assertEqual(azimuth, target_azimuth)

            dx, dy = g._calculate_helmert_offsets(scale=scale, rotation=azimuth)
            self.assertAlmostEqual(dx, x_offset)
            self.assertAlmostEqual(dy, y_offset)
