# Generated by Django 2.2.20 on 2021-10-07 19:18

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0031_auto_20201107_2241'),
        ('layers', '0034_auto_20210329_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitDocumentLink',
            fields=[
                ('documentresourcelink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.DocumentResourceLink')),
            ],
            options={
                'verbose_name': 'Split Document Link',
                'verbose_name_plural': 'Split Document Links',
            },
            bases=('documents.documentresourcelink',),
        ),
        migrations.CreateModel(
            name='SplitSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments_used', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('cutlines_used', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Split Session',
                'verbose_name_plural': 'Split Sessions',
            },
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('cutlines', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
        ),
        migrations.CreateModel(
            name='GeoreferenceSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcps_used', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('transformation_used', models.CharField(blank=True, max_length=20, null=True)),
                ('crs_epsg_used', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unstarted', 'unstarted'), ('failed', 'failed'), ('georeferencing', 'georeferencing'), ('layercreation', 'layercreation'), ('success', 'success')], default='unstarted', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Georeference Session',
                'verbose_name_plural': 'Georeference Sessions',
            },
        ),
        migrations.CreateModel(
            name='GCPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_epsg', models.IntegerField(blank=True, null=True)),
                ('transformation', models.CharField(blank=True, choices=[('tps', 'tps'), ('poly1', 'poly1'), ('poly2', 'poly2'), ('poly3', 'poly3')], max_length=20, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
            options={
                'verbose_name': 'GCP Group',
                'verbose_name_plural': 'GCP Groups',
            },
        ),
        migrations.CreateModel(
            name='GCP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pixel_x', models.IntegerField(blank=True, null=True)),
                ('pixel_y', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('gcp_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georeference.GCPGroup')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GCP',
                'verbose_name_plural': 'GCPs',
            },
        ),
    ]
