# Generated by Django 2.2.16 on 2021-07-16 19:56

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0031_auto_20201107_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
            options={
                'verbose_name': 'Split Session',
                'verbose_name_plural': 'Split Sessions',
            },
        ),
        migrations.CreateModel(
            name='SplitLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='documents.Document')),
                ('parent_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='documents.Document')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georeference.SplitSession')),
            ],
            options={
                'verbose_name': 'Split Link',
                'verbose_name_plural': 'Split Links',
            },
        ),
        migrations.CreateModel(
            name='GCPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_epsg', models.IntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
            ],
            options={
                'verbose_name': 'GCP Group',
                'verbose_name_plural': 'GCP Groups',
            },
        ),
        migrations.CreateModel(
            name='GCP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pixel_x', models.IntegerField(blank=True, null=True)),
                ('pixel_y', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('gcp_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georeference.GCPGroup')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GCP',
                'verbose_name_plural': 'GCPs',
            },
        ),
    ]
