# Generated by Django 2.2.20 on 2022-02-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georeferencesession',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.Layer'),
        ),
    ]
