# Generated by Django 2.2.20 on 2021-11-17 15:16

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0034_auto_20210329_1458'),
        ('documents', '0031_auto_20201107_2241'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georeference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoreferencedDocumentLink',
            fields=[
                ('documentresourcelink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.DocumentResourceLink')),
            ],
            options={
                'verbose_name': 'Georeferenced Document Link',
                'verbose_name_plural': 'Georeferenced Document Links',
            },
            bases=('documents.documentresourcelink',),
        ),
        migrations.CreateModel(
            name='MaskSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mask Session',
                'verbose_name_plural': 'Mask Sessions',
            },
        ),
        migrations.CreateModel(
            name='LayerMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
            ],
        ),
    ]
