# Generated by Django 2.2.16 on 2021-09-13 22:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitsession',
            name='cut_lines',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
