# Generated by Django 2.2.20 on 2021-10-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='no_split_needed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='splitsession',
            name='no_split_needed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
