# Generated by Django 2.2.20 on 2021-11-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20201107_2241'),
        ('georeference', '0002_layermask_masksession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoreferencedDocumentLink',
            fields=[
                ('documentresourcelink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.DocumentResourceLink')),
            ],
            options={
                'verbose_name': 'Georeferenced Document Link',
                'verbose_name_plural': 'Georeferenced Document Links',
            },
            bases=('documents.documentresourcelink',),
        ),
    ]
