# Generated by Django 2.2.20 on 2021-10-01 20:15

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0034_auto_20210329_1458'),
        ('documents', '0031_auto_20201107_2241'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georeference', '0002_splitsession_cut_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpgroup',
            name='transformation',
            field=models.CharField(blank=True, choices=[('tps', 'tps'), ('poly1', 'poly1'), ('poly2', 'poly2'), ('poly3', 'poly3')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='GeoreferenceSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcps_used', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('transformation_used', models.CharField(blank=True, max_length=20, null=True)),
                ('crs_epsg_used', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unstarted', 'unstarted'), ('failed', 'failed'), ('georeferencing', 'georeferencing'), ('layercreation', 'layercreation'), ('success', 'success')], default='unstarted', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Georeference Session',
                'verbose_name_plural': 'Georeference Sessions',
            },
        ),
    ]
