# Generated by Django 2.2.20 on 2021-11-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0002_georeferenceddocumentlink_layermask_masksession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georeferencesession',
            name='status',
            field=models.CharField(default='initializing', max_length=20),
        ),
    ]
