# Generated by Django 2.2.20 on 2022-03-09 20:54

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0034_auto_20210329_1458'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0031_auto_20201107_2241'),
        ('georeference', '0002_auto_20220214_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('p', 'Preparation'), ('g', 'Georeference'), ('t', 'Trim')], max_length=1)),
                ('stage', models.CharField(choices=[('input', 'Input'), ('processing', 'Processing'), ('success', 'Success'), ('failure', 'Failure')], default='input', max_length=11)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_run', models.DateTimeField(blank=True, null=True)),
                ('status_note', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Document')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.Layer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeorefSession',
            fields=[
            ],
            options={
                'verbose_name': 'Georeference Session',
                'verbose_name_plural': 'Georeference Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('georeference.sessionbase',),
        ),
        migrations.CreateModel(
            name='PrepSession',
            fields=[
            ],
            options={
                'verbose_name': 'Preparation Session',
                'verbose_name_plural': 'Preparation Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('georeference.sessionbase',),
        ),
        migrations.CreateModel(
            name='TrimSession',
            fields=[
            ],
            options={
                'verbose_name': 'Trim Session',
                'verbose_name_plural': 'Trim Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('georeference.sessionbase',),
        ),
    ]
