# Generated by Django 2.2.20 on 2021-11-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0003_auto_20211117_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georeferencesession',
            name='status',
            field=models.CharField(default='initializing', max_length=100),
        ),
    ]
