# Generated by Django 2.2.20 on 2022-10-11 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import georeference.models.resources
import georeference.storage


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('georeference', '0004_auto_20220412_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('document', 'Document'), ('layer', 'Layer')], max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attribution', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(blank=True, choices=[('unprepared', 'Unprepared'), ('needs review', 'Needs Review'), ('splitting', 'Splitting - in progress'), ('split', 'Split'), ('prepared', 'Prepared'), ('georeferencing', 'Georeferencing - in progress'), ('georeferenced', 'Georeferenced')], default='unprepared', max_length=50, null=True)),
                ('x0', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('y0', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('x1', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('y1', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('epsg', models.IntegerField(blank=True, null=True)),
                ('favorite_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, storage=georeference.storage.OverwriteStorage(), upload_to=georeference.models.resources.set_upload_location)),
                ('thumbnail', models.FileField(blank=True, max_length=255, null=True, storage=georeference.storage.OverwriteStorage(), upload_to='thumbnails')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('georeference.itembase',),
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
            ],
            options={
                'verbose_name': 'Layer',
                'verbose_name_plural': 'Layers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('georeference.itembase',),
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField()),
                ('link_type', models.CharField(choices=[('split', 'split'), ('georeference', 'georeference')], max_length=25)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='georeference.Document')),
            ],
        ),
        migrations.AddField(
            model_name='sessionbase',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc', to='georeference.Document'),
        ),
        migrations.AddField(
            model_name='sessionbase',
            name='lyr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lyr', to='georeference.Layer'),
        ),
    ]
