# Generated by Django 2.2.20 on 2022-10-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0005_auto_20221011_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpgroup',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georeference.Document'),
        ),
        migrations.AlterField(
            model_name='gcpgroup',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Document'),
        ),
    ]
