# Generated by Django 2.2.20 on 2022-12-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0007_auto_20221118_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='georeferenceddocumentlink',
            name='documentresourcelink_ptr',
        ),
        migrations.RemoveField(
            model_name='layermask',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='splitdocumentlink',
            name='documentresourcelink_ptr',
        ),
        migrations.DeleteModel(
            name='TrimSession',
        ),
        migrations.RemoveField(
            model_name='gcpgroup',
            name='document',
        ),
        migrations.RemoveField(
            model_name='sessionbase',
            name='document',
        ),
        migrations.RemoveField(
            model_name='sessionbase',
            name='layer',
        ),
        migrations.AlterField(
            model_name='sessionbase',
            name='type',
            field=models.CharField(blank=True, choices=[('p', 'Preparation'), ('g', 'Georeference')], max_length=1),
        ),
        migrations.DeleteModel(
            name='GeoreferencedDocumentLink',
        ),
        migrations.DeleteModel(
            name='LayerMask',
        ),
        migrations.DeleteModel(
            name='SplitDocumentLink',
        ),
    ]
