# Generated by Django 2.2.20 on 2021-10-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='month',
            field=models.CharField(blank=True, choices=[(1, 'JAN.'), (2, 'FEB.'), (3, 'MAR.'), (4, 'APR.'), (5, 'MAY.'), (6, 'JUN.'), (7, 'JUL.'), (8, 'AUG.'), (9, 'SEP.'), (10, 'OCT.'), (11, 'NOV.'), (12, 'DEC.')], max_length=10, null=True),
        ),
    ]
