# Generated by Django 2.2.20 on 2023-03-31 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='extent',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='volume',
            name='locales',
            field=models.ManyToManyField(blank=True, to='places.Place'),
        ),
    ]
