# Generated by Django 3.2.18 on 2023-05-20 12:54

from django.db import migrations, models
import ohmg.georeference.storage

class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='mosaic_json',
            field=models.FileField(blank=True, max_length=255, null=True, storage=ohmg.georeference.storage.OverwriteStorage(), upload_to='mosaics'),
        ),
    ]
