# Generated by Django 3.2.18 on 2023-05-20 12:54

from django.db import migrations, models
import georeference.storage

def transfer_mosaic_json(apps, schema_editor):
    try:
        from loc_insurancemaps.models import Volume
    except ImportError:
        return
    
    for v in Volume.objects.all():
        print("--------")
        print("geotiff:" + str(v.mosaic_geotiff))
        print("json:" + str(v.mosaic_json))
        if v.mosaic_geotiff and v.mosaic_geotiff.path.endswith(".json"):
            v.mosaic_json = v.mosaic_geotiff
            v.save()

        print("geotiff:" + str(v.mosaic_geotiff))
        print("json:" + str(v.mosaic_json))

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='mosaic_json',
            field=models.FileField(blank=True, max_length=255, null=True, storage=georeference.storage.OverwriteStorage(), upload_to='mosaics'),
        ),
        migrations.RunPython(transfer_mosaic_json, reverse_func)
    ]
