# Generated by Django 2.2.20 on 2021-12-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='load_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
