# Generated by Django 2.2.20 on 2022-02-09 17:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import loc_insurancemaps.models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0002_volume_load_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='ordered_layers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=loc_insurancemaps.models.default_ordered_layers_dict, null=True),
        ),
    ]
