# Generated by Django 2.2.20 on 2022-03-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0003_volume_ordered_layers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='index_layers',
        ),
    ]
