# Generated by Django 2.2.20 on 2022-03-02 21:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations

from loc_insurancemaps.models import Volume

def update_volume_lookups(apps, schema_editor):
    """Populate the new lookup fields on all volumes."""

    for volume in Volume.objects.all():
        volume.populate_lookups()

class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0004_remove_volume_index_layers'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='document_lookup',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='layer_lookup',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RunPython(update_volume_lookups)
    ]
