# Generated by Django 2.2.20 on 2022-08-04 18:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0007_volume_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='multimask',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
