# Generated by Django 2.2.20 on 2022-09-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0008_volume_multimask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('state', 'State'), ('county', 'County'), ('parish', 'Parish'), ('borough', 'Borough'), ('census area', 'Census Area'), {'independent city', 'Independent City'}, ('city', 'City'), ('town', 'Town'), ('village', 'Village'), ('other', 'Other')], max_length=20)),
                ('display_name', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('direct_parents', models.ManyToManyField(to='loc_insurancemaps.Place')),
            ],
        ),
        migrations.AddField(
            model_name='volume',
            name='locale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locale', to='loc_insurancemaps.Place'),
        ),
        migrations.AddField(
            model_name='volume',
            name='places',
            field=models.ManyToManyField(related_name='places', to='loc_insurancemaps.Place'),
        ),
    ]
