# Generated by Django 2.2.20 on 2022-09-26 20:50

from django.db import migrations, models
import georeference.storage


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0009_auto_20220902_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='mosaic_geotiff',
            field=models.FileField(blank=True, max_length=255, null=True, storage=georeference.storage.OverwriteStorage(), upload_to='mosaics'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'JAN.'), (2, 'FEB.'), (3, 'MAR.'), (4, 'APR.'), (5, 'MAY.'), (6, 'JUN.'), (7, 'JUL.'), (8, 'AUG.'), (9, 'SEP.'), (10, 'OCT.'), (11, 'NOV.'), (12, 'DEC.')], null=True),
        ),
    ]
