# Generated by Django 2.2.20 on 2022-10-11 23:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import loc_insurancemaps.models


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0005_auto_20221011_1748'),
        ('loc_insurancemaps', '0010_auto_20220926_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georeference.Document'),
        ),
        migrations.AddField(
            model_name='volume',
            name='sorted_layers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=loc_insurancemaps.models.default_sorted_layers_dict),
        ),
    ]
