# Generated by Django 2.2.20 on 2022-10-12 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0011_auto_20221011_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georeference.Document'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Document'),
        ),
    ]
