# Generated by Django 2.2.20 on 2022-12-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0012_auto_20221012_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='document',
        ),
        migrations.DeleteModel(
            name='FullThumbnail',
        ),
    ]
