# Generated by Django 2.2.20 on 2023-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0013_auto_20221221_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='volume_count',
            field=models.IntegerField(default=0, help_text='Number of volumes attached to this place'),
        ),
        migrations.AddField(
            model_name='place',
            name='volume_count_inclusive',
            field=models.IntegerField(default=0, help_text='Number of volumes attached to this place and any of its descendants'),
        ),
    ]
