# Generated by Django 2.2.20 on 2023-03-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0014_auto_20230317_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='regions',
        ),
    ]
