# Generated by Django 2.2.20 on 2023-03-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0015_remove_volume_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='slug',
        ),
    ]
