# Generated by Django 2.2.20 on 2023-03-22 14:57

from django.db import migrations, models

def migrate_locale_to_locales(apps, schema_editor):
    try:
        from loc_insurancemaps.models import Volume
        from places.models import Place
    except ImportError:
        return
    for volume in Volume.objects.all():
        place = Place.objects.get(slug=volume.locale.slug)
        volume.locales.add(place)

def reverse_migration(*args):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('loc_insurancemaps', '0016_remove_volume_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='places',
        ),
        migrations.AddField(
            model_name='volume',
            name='locales',
            field=models.ManyToManyField(related_name='places', to='places.Place'),
        ),
        migrations.RunPython(migrate_locale_to_locales, reverse_migration)
    ]
