# Generated by Django 2.2.20 on 2023-03-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0017_auto_20230322_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='locales',
            field=models.ManyToManyField(blank=True, null=True, to='places.Place'),
        ),
    ]
