# Generated by Django 2.2.20 on 2023-03-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0018_auto_20230322_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='locale',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
