# Generated by Django 3.2.18 on 2024-04-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API Key'},
        ),
    ]
