# Generated by Django 3.2.18 on 2025-12-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_apikey_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gcp_ct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gsesh_ct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='load_ct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='psesh_ct',
            field=models.IntegerField(default=0),
        ),
    ]
