# Generated by Django 4.2.27 on 2026-01-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20251202_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
