# Generated by Django 3.2.18 on 2023-06-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembase',
            name='status',
            field=models.CharField(blank=True, choices=[('unprepared', 'Unprepared'), ('needs review', 'Needs Review'), ('splitting', 'Splitting - in progress'), ('split', 'Split'), ('prepared', 'Prepared'), ('georeferencing', 'Georeferencing - in progress'), ('georeferenced', 'Georeferenced'), ('nonmap', 'Non-Map')], default='unprepared', max_length=50, null=True),
        ),
    ]
