# Generated by Django 3.2.18 on 2025-09-25 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250915_1937'),
        ('georeference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbase',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.map'),
        ),
    ]
