# Generated by Django 4.2.27 on 2026-06-05 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_layerset_xyz_tiles_prefix'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('georeference', '0002_sessionbase_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_queued', models.DateTimeField(blank=True, null=True)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('load_documents', 'load_documents'), ('split_document', 'split_document'), ('region_to_cog', 'region_to_cog'), ('layerset_to_cog', 'layerset_to_cog'), ('layerset_to_xyz', 'layerset_to_xyz')], max_length=25)),
                ('stage', models.CharField(blank=True, choices=[('queued', 'queued'), ('running', 'running'), ('completed', 'completed'), ('errored', 'errored')], max_length=25, null=True)),
                ('run_duration', models.IntegerField(blank=True, null=True)),
                ('target_id', models.PositiveIntegerField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.map')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
