# Generated by Django 3.2.18 on 2024-02-26 12:36

from django.db import migrations, models
import django.db.models.deletion
import ohmg.georeference.storage


class Migration(migrations.Migration):

    dependencies = [
        ('loc_insurancemaps', '0004_auto_20240116_1016'),
        ('georeference', '0002_alter_itembase_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('display_name', models.CharField(max_length=50)),
                ('is_geospatial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualResourceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimask', models.JSONField(blank=True, null=True)),
                ('mosaic_geotiff', models.FileField(blank=True, max_length=255, null=True, storage=ohmg.georeference.storage.OverwriteStorage(), upload_to='mosaics')),
                ('mosaic_json', models.FileField(blank=True, max_length=255, null=True, storage=ohmg.georeference.storage.OverwriteStorage(), upload_to='mosaics')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='georeference.setcategory')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loc_insurancemaps.volume')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
            ],
            options={
                'verbose_name': 'DocumentSet',
                'verbose_name_plural': 'DocumentSets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('georeference.virtualresourceset',),
        ),
        migrations.CreateModel(
            name='LayerSet',
            fields=[
            ],
            options={
                'verbose_name': 'LayerSet',
                'verbose_name_plural': 'LayerSets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('georeference.virtualresourceset',),
        ),
        migrations.AddField(
            model_name='itembase',
            name='vrs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georeference.virtualresourceset'),
        ),
    ]
