# Generated by Django 4.2.27 on 2026-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcpgroup',
            name='transformation',
            field=models.CharField(blank=True, choices=[('helmert', 'helmert'), ('tps', 'tps'), ('poly1', 'poly1'), ('poly2', 'poly2'), ('poly3', 'poly3')], max_length=20, null=True),
        ),
    ]
