# Generated by Django 3.2.18 on 2024-04-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0003_auto_20240302_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setcategory',
            options={'verbose_name_plural': 'Set Categories'},
        ),
    ]
