# Generated by Django 3.2.18 on 2024-06-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('loc_insurancemaps', '0004_auto_20240116_1016'),
        ('georeference', '0005_auto_20240617_1102'),
    ]

    operations = [
        migrations.RenameModel('AnnotationSet','LayerSet'),
    ]
