# Generated by Django 3.2.18 on 2024-06-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0006_rename_annotationset_layerset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetCategory',
            new_name='LayerSetCategory',
        ),
    ]
