# Generated by Django 3.2.18 on 2024-08-21 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('georeference', '0007_rename_setcategory_layersetcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbase',
            name='doc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.document'),
        ),
        migrations.AddField(
            model_name='sessionbase',
            name='lyr2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.layer'),
        ),
        migrations.AddField(
            model_name='sessionbase',
            name='reg2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
    ]
