# Generated by Django 3.2.18 on 2024-08-23 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('georeference', '0007_rename_setcategory_layersetcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerset',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.map'),
        ),
        migrations.AddField(
            model_name='sessionbase',
            name='doc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.document'),
        ),
        migrations.AddField(
            model_name='sessionbase',
            name='lyr2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.layer'),
        ),
        migrations.AddField(
            model_name='sessionbase',
            name='reg2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
        migrations.CreateModel(
            name='SessionLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField()),
                ('expiration', models.DateTimeField(default=datetime.datetime(2024, 8, 23, 19, 31, 39, 518275))),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='georeference.sessionbase')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Lock',
                'verbose_name_plural': 'Session Locks',
            },
        ),
    ]
