# Generated by Django 3.2.18 on 2024-08-31 18:53

from django.db import migrations, models
import ohmg.georeference.models.sessions


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0008_auto_20240823_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlock',
            name='expiration',
            field=models.DateTimeField(default=ohmg.georeference.models.sessions.default_expiration_time),
        ),
    ]
