# Generated by Django 3.2.18 on 2024-09-03 20:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0009_alter_sessionlock_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerset',
            name='extent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4),
        ),
    ]
