# Generated by Django 3.2.18 on 2024-11-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0009_auto_20240914_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerset',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='layersetcategory',
            name='is_geospatial',
        ),
    ]
