# Generated by Django 3.2.18 on 2025-01-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0010_remove_layerset_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcpgroup',
            name='doc',
        ),
    ]
