# Generated by Django 3.2.18 on 2025-01-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0011_remove_gcpgroup_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionbase',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='sessionbase',
            name='lyr',
        ),
    ]
