# Generated by Django 3.2.18 on 2025-01-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0012_auto_20250119_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentLink',
        ),
    ]
