# Generated by Django 3.2.18 on 2025-01-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0013_delete_documentlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembase',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='itembase',
            name='vrs',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='LayerV1',
        ),
        migrations.DeleteModel(
            name='ItemBase',
        ),
    ]
