# Generated by Django 3.2.18 on 2025-01-23 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250120_2212'),
        ('georeference', '0014_auto_20250119_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerset',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layerset_old', to='core.map'),
        ),
    ]
