# Generated by Django 3.2.18 on 2025-01-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georeference', '0015_alter_layerset_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayerSet',
        ),
        migrations.DeleteModel(
            name='LayerSetCategory',
        ),
    ]
