# Generated by Django 3.2.18 on 2025-02-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_layer_layerset'),
        ('georeference', '0016_auto_20250124_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpgroup',
            name='region2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
