# Generated by Django 3.2.18 on 2025-11-12 22:06

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(blank=True, max_length=255, null=True, upload_to='partner-logos')),
                ('url', models.CharField(blank=True, max_length=400, null=True)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
