# Generated by Django 3.2.18 on 2025-12-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_redirect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Redirect',
        ),
    ]
