# Generated by Django 4.2.27 on 2026-02-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_name', models.CharField(max_length=200)),
                ('source_href', models.CharField(max_length=200)),
                ('pmtiles_url', models.CharField(max_length=200)),
                ('locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place')),
            ],
        ),
    ]
